name: Breadboard
favicon: null
layout_spectrum: 0.14264549524523318
typography_spectrum: 0.5160512579604983
title: Breadboard
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9442591343540698
  lightness: 0.8745163583662361
  saturation: 0.35066466173157096
  rhythmicContrast: 0.45978791848756373
purpose: []
